# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: en
title: Sorrento Dental Clinic
email: reception@sorrento.dental
description: Sorrento Dental Clinic in Sorrento, Western Australia. We provide a range of dental services including general, cosmetic, and emergency dentistry.
# Webmentions - leave blank (remove "yes") if you would not like to receive & display webmentions from other sites
webmentions:

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sorrento.dental" # the base hostname & protocol for your site

# Can be over ridden with author: in Front Matter
author: Reece Orbuck

# Expecting a full url, not relative to site.url
author_img: https://avatars3.githubusercontent.com/u/3083652

# Build settings
markdown: kramdown
gems:
  - github-pages
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist

paginate: 5

# Google Analytics
google_analytics: UA-131758713-1
